/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "D:\\code\\wang-blog\\wcp-blog\\node_modules\\@vuepress\\core\\lib\\client\\components\\GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-56e9ac57",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-56e9ac57").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-7ccb1084",
    path: "/handbook/Byte/pubuliu.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7ccb1084").then(next)
    },
  },
  {
    name: "v-c8965edc",
    path: "/handbook/Byte/object.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-c8965edc").then(next)
    },
  },
  {
    name: "v-e5d660b8",
    path: "/handbook/Byte/array.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-e5d660b8").then(next)
    },
  },
  {
    name: "v-33e5d3b4",
    path: "/handbook/Byte/sanleibuju.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-33e5d3b4").then(next)
    },
  },
  {
    name: "v-64f56220",
    path: "/handbook/ES6/for-in-of.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-64f56220").then(next)
    },
  },
  {
    name: "v-e18cb5c8",
    path: "/handbook/ES6/async-await.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-e18cb5c8").then(next)
    },
  },
  {
    name: "v-7d8b6320",
    path: "/handbook/ES6/promise.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7d8b6320").then(next)
    },
  },
  {
    name: "v-1c4235da",
    path: "/handbook/JavaScript/ajax.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1c4235da").then(next)
    },
  },
  {
    name: "v-7ae7c580",
    path: "/handbook/JavaScript/kaobei.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7ae7c580").then(next)
    },
  },
  {
    name: "v-6356b144",
    path: "/handbook/JavaScript/leixingzhuanghuan.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6356b144").then(next)
    },
  },
  {
    name: "v-7e5b235e",
    path: "/handbook/JavaScript/this.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7e5b235e").then(next)
    },
  },
  {
    name: "v-e6653238",
    path: "/handbook/JavaScript/xianshibangding.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-e6653238").then(next)
    },
  },
  {
    name: "v-274fd1a4",
    path: "/handbook/JavaScript/jicheng.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-274fd1a4").then(next)
    },
  },
  {
    name: "v-2a93ae44",
    path: "/handbook/JavaScript/zuoyongyu.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2a93ae44").then(next)
    },
  },
  {
    name: "v-3511e1f4",
    path: "/handbook/JavaScript/yuanxing.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3511e1f4").then(next)
    },
  },
  {
    name: "v-6ad44a24",
    path: "/handbook/Node/kuayu.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6ad44a24").then(next)
    },
  },
  {
    name: "v-1fd58c02",
    path: "/handbook/Vue/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1fd58c02").then(next)
    },
  },
  {
    path: "/handbook/Vue/index.html",
    redirect: "/handbook/Vue/"
  },
  {
    name: "v-7e563884",
    path: "/handbook/andition/bianpinghua.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7e563884").then(next)
    },
  },
  {
    name: "v-82bfd1c4",
    path: "/handbook/Vue/router.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-82bfd1c4").then(next)
    },
  },
  {
    name: "v-14043cc4",
    path: "/views/Resume/resume.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-14043cc4").then(next)
    },
  },
  {
    name: "v-a32dc94c",
    path: "/views/About/author.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-a32dc94c").then(next)
    },
  },
  {
    name: "v-5f3aa964",
    path: "/handbook/andition/promise.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5f3aa964").then(next)
    },
  },
  {
    name: "v-2056eaa4",
    path: "/handbook/andition/fabudingyue.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2056eaa4").then(next)
    },
  },
  {
    name: "v-1e4f5d4a",
    path: "/views/other/guide.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1e4f5d4a").then(next)
    },
  },
  {
    name: "v-b1564aac",
    path: "/tag/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tags", "v-b1564aac").then(next)
    },
    meta: {"pid":"tags","id":"tags"}
  },
  {
    path: "/tag/index.html",
    redirect: "/tag/"
  },
  {
    name: "v-ef9325c4",
    path: "/categories/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("FrontmatterKey", "v-ef9325c4").then(next)
    },
    meta: {"pid":"categories","id":"categories"}
  },
  {
    path: "/categories/index.html",
    redirect: "/categories/"
  },
  {
    name: "v-6319eb4e",
    path: "/timeline/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("TimeLines", "v-6319eb4e").then(next)
    },
    meta: {"pid":"timeline","id":"timeline"}
  },
  {
    path: "/timeline/index.html",
    redirect: "/timeline/"
  },
  {
    name: "v-3259a754",
    path: "/tag/CSS/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-3259a754").then(next)
    },
    meta: {"pid":"tags","id":"CSS"}
  },
  {
    path: "/tag/CSS/index.html",
    redirect: "/tag/CSS/"
  },
  {
    name: "v-2393e274",
    path: "/tag/Object/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-2393e274").then(next)
    },
    meta: {"pid":"tags","id":"Object"}
  },
  {
    path: "/tag/Object/index.html",
    redirect: "/tag/Object/"
  },
  {
    name: "v-7d137840",
    path: "/tag/Array/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-7d137840").then(next)
    },
    meta: {"pid":"tags","id":"Array"}
  },
  {
    path: "/tag/Array/index.html",
    redirect: "/tag/Array/"
  },
  {
    name: "v-3257dcde",
    path: "/tag/ES6/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-3257dcde").then(next)
    },
    meta: {"pid":"tags","id":"ES6"}
  },
  {
    path: "/tag/ES6/index.html",
    redirect: "/tag/ES6/"
  },
  {
    name: "v-5f66a358",
    path: "/tag/javaScript/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-5f66a358").then(next)
    },
    meta: {"pid":"tags","id":"javaScript"}
  },
  {
    path: "/tag/javaScript/index.html",
    redirect: "/tag/javaScript/"
  },
  {
    name: "v-d74bd976",
    path: "/tag/深浅拷贝/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-d74bd976").then(next)
    },
    meta: {"pid":"tags","id":"深浅拷贝"}
  },
  {
    path: "/tag/深浅拷贝/index.html",
    redirect: "/tag/深浅拷贝/"
  },
  {
    name: "v-0b8093b7",
    path: "/tag/类型转换/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-0b8093b7").then(next)
    },
    meta: {"pid":"tags","id":"类型转换"}
  },
  {
    path: "/tag/类型转换/index.html",
    redirect: "/tag/类型转换/"
  },
  {
    name: "v-c784ecce",
    path: "/tag/继承/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-c784ecce").then(next)
    },
    meta: {"pid":"tags","id":"继承"}
  },
  {
    path: "/tag/继承/index.html",
    redirect: "/tag/继承/"
  },
  {
    name: "v-0df5b1b6",
    path: "/tag/八股文/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-0df5b1b6").then(next)
    },
    meta: {"pid":"tags","id":"八股文"}
  },
  {
    path: "/tag/八股文/index.html",
    redirect: "/tag/八股文/"
  },
  {
    name: "v-67cf2c0a",
    path: "/tag/跨域/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-67cf2c0a").then(next)
    },
    meta: {"pid":"tags","id":"跨域"}
  },
  {
    path: "/tag/跨域/index.html",
    redirect: "/tag/跨域/"
  },
  {
    name: "v-322a45da",
    path: "/tag/vue/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-322a45da").then(next)
    },
    meta: {"pid":"tags","id":"vue"}
  },
  {
    path: "/tag/vue/index.html",
    redirect: "/tag/vue/"
  },
  {
    name: "v-2892531a",
    path: "/tag/扁平化/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-2892531a").then(next)
    },
    meta: {"pid":"tags","id":"扁平化"}
  },
  {
    path: "/tag/扁平化/index.html",
    redirect: "/tag/扁平化/"
  },
  {
    name: "v-4081041c",
    path: "/tag/router/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-4081041c").then(next)
    },
    meta: {"pid":"tags","id":"router"}
  },
  {
    path: "/tag/router/index.html",
    redirect: "/tag/router/"
  },
  {
    name: "v-19493022",
    path: "/tag/面试题/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-19493022").then(next)
    },
    meta: {"pid":"tags","id":"面试题"}
  },
  {
    path: "/tag/面试题/index.html",
    redirect: "/tag/面试题/"
  },
  {
    name: "v-1d861698",
    path: "/tag/发布订阅/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-1d861698").then(next)
    },
    meta: {"pid":"tags","id":"发布订阅"}
  },
  {
    path: "/tag/发布订阅/index.html",
    redirect: "/tag/发布订阅/"
  },
  {
    name: "v-60d1e5a9",
    path: "/categories/Byte/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Category", "v-60d1e5a9").then(next)
    },
    meta: {"pid":"categories","id":"Byte"}
  },
  {
    path: "/categories/Byte/index.html",
    redirect: "/categories/Byte/"
  },
  {
    name: "v-7eff4a05",
    path: "/categories/ES6/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Category", "v-7eff4a05").then(next)
    },
    meta: {"pid":"categories","id":"ES6"}
  },
  {
    path: "/categories/ES6/index.html",
    redirect: "/categories/ES6/"
  },
  {
    name: "v-081e6844",
    path: "/categories/JavaScript/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Category", "v-081e6844").then(next)
    },
    meta: {"pid":"categories","id":"JavaScript"}
  },
  {
    path: "/categories/JavaScript/index.html",
    redirect: "/categories/JavaScript/"
  },
  {
    name: "v-617637ef",
    path: "/categories/Node/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Category", "v-617637ef").then(next)
    },
    meta: {"pid":"categories","id":"Node"}
  },
  {
    path: "/categories/Node/index.html",
    redirect: "/categories/Node/"
  },
  {
    name: "v-7f0789a7",
    path: "/categories/Vue/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Category", "v-7f0789a7").then(next)
    },
    meta: {"pid":"categories","id":"Vue"}
  },
  {
    path: "/categories/Vue/index.html",
    redirect: "/categories/Vue/"
  },
  {
    name: "v-6eaeda0b",
    path: "/categories/andition/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Category", "v-6eaeda0b").then(next)
    },
    meta: {"pid":"categories","id":"andition"}
  },
  {
    path: "/categories/andition/index.html",
    redirect: "/categories/andition/"
  },
  {
    path: '*',
    component: GlobalLayout
  }
]