/**
 * Generated by "@vuepress/plugin-blog"
 */
export default {
  "tags": {
    "CSS": {
      "key": "CSS",
      "scope": "tags",
      "path": "/tag/CSS/",
      "pageKeys": [
        "v-1336e3a4",
        "v-3262d474"
      ]
    },
    "Array": {
      "key": "Array",
      "scope": "tags",
      "path": "/tag/Array/",
      "pageKeys": [
        "v-098c0b94"
      ]
    },
    "Object": {
      "key": "Object",
      "scope": "tags",
      "path": "/tag/Object/",
      "pageKeys": [
        "v-51665efc"
      ]
    },
    "ES6": {
      "key": "ES6",
      "scope": "tags",
      "path": "/tag/ES6/",
      "pageKeys": [
        "v-6e8ab50c",
        "v-065b6340",
        "v-7c3bd6e0"
      ]
    },
    "javaScript": {
      "key": "javaScript",
      "scope": "tags",
      "path": "/tag/javaScript/",
      "pageKeys": [
        "v-08d9746c"
      ]
    },
    "继承": {
      "key": "继承",
      "scope": "tags",
      "path": "/tag/继承/",
      "pageKeys": [
        "v-c99da4d8",
        "v-5dac334e"
      ]
    },
    "类型转换": {
      "key": "类型转换",
      "scope": "tags",
      "path": "/tag/类型转换/",
      "pageKeys": [
        "v-4b62b534"
      ]
    },
    "深浅拷贝": {
      "key": "深浅拷贝",
      "scope": "tags",
      "path": "/tag/深浅拷贝/",
      "pageKeys": [
        "v-71f3b530"
      ]
    },
    "八股文": {
      "key": "八股文",
      "scope": "tags",
      "path": "/tag/八股文/",
      "pageKeys": [
        "v-1fd8e2d4",
        "v-360c01e4",
        "v-54f4db98"
      ]
    },
    "跨域": {
      "key": "跨域",
      "scope": "tags",
      "path": "/tag/跨域/",
      "pageKeys": [
        "v-3168f3d8"
      ]
    },
    "router": {
      "key": "router",
      "scope": "tags",
      "path": "/tag/router/",
      "pageKeys": [
        "v-3b17530e"
      ]
    },
    "发布订阅": {
      "key": "发布订阅",
      "scope": "tags",
      "path": "/tag/发布订阅/",
      "pageKeys": [
        "v-696e62d8"
      ]
    },
    "面试题": {
      "key": "面试题",
      "scope": "tags",
      "path": "/tag/面试题/",
      "pageKeys": [
        "v-a2f10558"
      ]
    },
    "扁平化": {
      "key": "扁平化",
      "scope": "tags",
      "path": "/tag/扁平化/",
      "pageKeys": [
        "v-29481c74"
      ]
    },
    "vue": {
      "key": "vue",
      "scope": "tags",
      "path": "/tag/vue/",
      "pageKeys": [
        "v-7812ddef"
      ]
    }
  },
  "categories": {
    "Byte": {
      "key": "Byte",
      "scope": "categories",
      "path": "/categories/Byte/",
      "pageKeys": [
        "v-1336e3a4",
        "v-098c0b94",
        "v-3262d474",
        "v-51665efc"
      ]
    },
    "ES6": {
      "key": "ES6",
      "scope": "categories",
      "path": "/categories/ES6/",
      "pageKeys": [
        "v-6e8ab50c",
        "v-065b6340",
        "v-7c3bd6e0"
      ]
    },
    "JavaScript": {
      "key": "JavaScript",
      "scope": "categories",
      "path": "/categories/JavaScript/",
      "pageKeys": [
        "v-08d9746c",
        "v-c99da4d8",
        "v-4b62b534",
        "v-71f3b530",
        "v-1fd8e2d4",
        "v-5dac334e",
        "v-360c01e4",
        "v-54f4db98"
      ]
    },
    "Node": {
      "key": "Node",
      "scope": "categories",
      "path": "/categories/Node/",
      "pageKeys": [
        "v-3168f3d8"
      ]
    },
    "Vue": {
      "key": "Vue",
      "scope": "categories",
      "path": "/categories/Vue/",
      "pageKeys": [
        "v-3b17530e",
        "v-7812ddef"
      ]
    },
    "andition": {
      "key": "andition",
      "scope": "categories",
      "path": "/categories/andition/",
      "pageKeys": [
        "v-696e62d8",
        "v-a2f10558",
        "v-29481c74"
      ]
    }
  },
  "timeline": {}
}