/**
 * Generated by "@vuepress/plugin-blog"
 */
export default {
  "tags": {
    "CSS": {
      "key": "CSS",
      "scope": "tags",
      "path": "/tag/CSS/",
      "pageKeys": [
        "v-7ccb1084",
        "v-33e5d3b4"
      ]
    },
    "Object": {
      "key": "Object",
      "scope": "tags",
      "path": "/tag/Object/",
      "pageKeys": [
        "v-c8965edc"
      ]
    },
    "Array": {
      "key": "Array",
      "scope": "tags",
      "path": "/tag/Array/",
      "pageKeys": [
        "v-e5d660b8"
      ]
    },
    "ES6": {
      "key": "ES6",
      "scope": "tags",
      "path": "/tag/ES6/",
      "pageKeys": [
        "v-64f56220",
        "v-e18cb5c8",
        "v-7d8b6320"
      ]
    },
    "javaScript": {
      "key": "javaScript",
      "scope": "tags",
      "path": "/tag/javaScript/",
      "pageKeys": [
        "v-1c4235da"
      ]
    },
    "深浅拷贝": {
      "key": "深浅拷贝",
      "scope": "tags",
      "path": "/tag/深浅拷贝/",
      "pageKeys": [
        "v-7ae7c580"
      ]
    },
    "类型转换": {
      "key": "类型转换",
      "scope": "tags",
      "path": "/tag/类型转换/",
      "pageKeys": [
        "v-6356b144"
      ]
    },
    "继承": {
      "key": "继承",
      "scope": "tags",
      "path": "/tag/继承/",
      "pageKeys": [
        "v-7e5b235e",
        "v-274fd1a4"
      ]
    },
    "八股文": {
      "key": "八股文",
      "scope": "tags",
      "path": "/tag/八股文/",
      "pageKeys": [
        "v-e6653238",
        "v-2a93ae44",
        "v-3511e1f4"
      ]
    },
    "跨域": {
      "key": "跨域",
      "scope": "tags",
      "path": "/tag/跨域/",
      "pageKeys": [
        "v-6ad44a24"
      ]
    },
    "vue": {
      "key": "vue",
      "scope": "tags",
      "path": "/tag/vue/",
      "pageKeys": [
        "v-1fd58c02"
      ]
    },
    "扁平化": {
      "key": "扁平化",
      "scope": "tags",
      "path": "/tag/扁平化/",
      "pageKeys": [
        "v-7e563884"
      ]
    },
    "router": {
      "key": "router",
      "scope": "tags",
      "path": "/tag/router/",
      "pageKeys": [
        "v-82bfd1c4"
      ]
    },
    "面试题": {
      "key": "面试题",
      "scope": "tags",
      "path": "/tag/面试题/",
      "pageKeys": [
        "v-5f3aa964"
      ]
    },
    "发布订阅": {
      "key": "发布订阅",
      "scope": "tags",
      "path": "/tag/发布订阅/",
      "pageKeys": [
        "v-2056eaa4"
      ]
    }
  },
  "categories": {
    "Byte": {
      "key": "Byte",
      "scope": "categories",
      "path": "/categories/Byte/",
      "pageKeys": [
        "v-7ccb1084",
        "v-c8965edc",
        "v-e5d660b8",
        "v-33e5d3b4"
      ]
    },
    "ES6": {
      "key": "ES6",
      "scope": "categories",
      "path": "/categories/ES6/",
      "pageKeys": [
        "v-64f56220",
        "v-e18cb5c8",
        "v-7d8b6320"
      ]
    },
    "JavaScript": {
      "key": "JavaScript",
      "scope": "categories",
      "path": "/categories/JavaScript/",
      "pageKeys": [
        "v-1c4235da",
        "v-7ae7c580",
        "v-6356b144",
        "v-7e5b235e",
        "v-e6653238",
        "v-274fd1a4",
        "v-2a93ae44",
        "v-3511e1f4"
      ]
    },
    "Node": {
      "key": "Node",
      "scope": "categories",
      "path": "/categories/Node/",
      "pageKeys": [
        "v-6ad44a24"
      ]
    },
    "Vue": {
      "key": "Vue",
      "scope": "categories",
      "path": "/categories/Vue/",
      "pageKeys": [
        "v-1fd58c02",
        "v-82bfd1c4"
      ]
    },
    "andition": {
      "key": "andition",
      "scope": "categories",
      "path": "/categories/andition/",
      "pageKeys": [
        "v-7e563884",
        "v-5f3aa964",
        "v-2056eaa4"
      ]
    }
  },
  "timeline": {}
}